export enum ActionTypes {
  CHECK_CARDS = "CHECK_CARDS",
  TIME_UP = "TIME_UP",
  HAS_WON = "HAS_WON",
  TURN_UP = "TURN_UP",
  BEFORE_CHECK = "BEFORE_CHECK",
  SUCCESS = "SUCCESS",
  RESET = "RESET",
}
